---
weight: 1
title: "Lost Sensitivity"
author: "Lenny Lin"
categories: ["Troubleshooting Database"]
tags: ["Fishbone Demo"]
toc: true
date: "2022-08-16"
lastmod: "2022-08-16"
---


<!--more-->

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

```{r, warning = F, include=F}
library(SixSigma)
library(qcc)
```


## SixSigma package
```{r, echo= F }


effect <- "Lost Sensitivity"
causes.gr <- c("MS", "LC", "Sample Preparation", "Human Failures")
causes <- vector(mode = "list", length = length(causes.gr))
causes[1] <- list(c("--- ESI", "--- EMV", "--- Ion Source"))
causes[2] <- list(c("--- Column Degration", "--- Contamination", "--- Pressure Traces"))
causes[3] <- list(c("--- Analyte Loss", "--- Washing solvent", "--- eluting solvent"))
causes[4] <- list(c("--- Wrong Injection"))
ss.ceDiag(effect, causes.gr, causes, main = "Sensitivity with LC-MS/MS", sub = "")
```



## QCC package
```{r}
cause.and.effect(cause=list(Measurements=c("Micrometers", "Microscopes", "Inspectors"),
                            Materials=c("Alloys", "Lubricants", "Suppliers"),
                            Personnel=c("Shifts", "Supervisors", "Training", "Operators"),
                            Environment=c("Condensation", "Moisture"),
                            Methods=c("Brake", "Engager", "Angle"),
                            Machines=c("Speed", "Lathes", "Bits", "Sockets")),
                 effect="Surface Flaws")

```

[Reference](https://fenxihuaxue.netlify.app/docs/01-mass-spec-lc-ms/part-05-troubleshooting/02_lcmsms_clinical_troubleshooting/)

