---
weight: 1
title: "Fishbone Demo"
author: "Lenny Lin"
date: 2022-08-16
categories: ["Troubleshooting Database"]
tags: ["Fishbone Demo", "Troubleshooting Demo"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Fishbone diagram

```{r, warning = F, echo= F }
library(SixSigma)

effect <- "Low Sensitivity"
causes.gr <- c("MS", "LC", "Sample Preparation", "Human Failures")
causes <- vector(mode = "list", length = length(causes.gr))
causes[1] <- list(c("--- ESI", "--- EMV", "--- Ion Source"))
causes[2] <- list(c("--- Column Degration", "--- Contamination", "--- Pressure Traces"))
causes[3] <- list(c("--- Analyte Loss", "--- Washing solvent", "--- eluting solvent"))
causes[4] <- list(c("--- Wrong Injection"))
ss.ceDiag(effect, causes.gr, causes, main = "Sensitivity with LC-MS/MS", sub = "")
```



```{r Abnormal peak shape, echo= F }


effect <- "Abnormal Peak Shape"
causes.gr <- c("","")
causes <- vector(mode = "list", length = length(causes.gr))
causes[1] <- list(c(""))
causes[2] <- list(c(""))
causes[3] <- list(c(""))
causes[4] <- list(c(""))
causes[5] <- list(c(""))
ss.ceDiag(effect, causes.gr, causes, main = "Abnormal Peak Shape: LC-MS/MS", sub = "")
```


```{r missing peak, echo= F }
effect <- "Missing Peak"
causes.gr <- c("","")
causes <- vector(mode = "list", length = length(causes.gr))
causes[1] <- list(c(""))
causes[2] <- list(c(""))
causes[3] <- list(c(""))
causes[4] <- list(c(""))
causes[5] <- list(c(""))
ss.ceDiag(effect, causes.gr, causes, main = "Missing Peak: LC-MS/MS", sub = "")

```


```{r , echo= F }
effect <- "Leak"
causes.gr <- c("Column Hardware","Connections")
causes <- vector(mode = "list", length = length(causes.gr))
causes[1] <- list(c("Incorrect"))
causes[2] <- list(c("b"))
causes[3] <- list(c(""))
causes[4] <- list(c(""))
causes[5] <- list(c(""))
ss.ceDiag(effect, causes.gr, causes, main = "Leak: LC-MS/MS", sub = "Pressure Traces")
```


```{r template, echo= F }
effect <- ""
causes.gr <- c("","")
causes <- vector(mode = "list", length = length(causes.gr))
causes[1] <- list(c(""))
causes[2] <- list(c(""))
causes[3] <- list(c(""))
causes[4] <- list(c(""))
causes[5] <- list(c(""))
ss.ceDiag(effect, causes.gr, causes, main = "", sub = "")
```


