---
weight: 
title: ""
author: "Lenny Lin"
categories: ["Troubleshooting Database"]
tags: ["Fishbone Demo"]
toc: true
date: "2022-08-16"
lastmod: "2022-08-16"
---


<!--more-->

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

```{r, warning = F, include=F}
library(SixSigma)
library(qcc)
```





```{r template, echo= F }
effect <- ""
causes.gr <- c("","")
causes <- vector(mode = "list", length = length(causes.gr))
causes[1] <- list(c(""))
causes[2] <- list(c(""))
causes[3] <- list(c(""))
causes[4] <- list(c(""))
causes[5] <- list(c(""))
ss.ceDiag(effect, causes.gr, causes, main = "", sub = "")
```


## QCC package
```{r, echo = F }
cause.and.effect(cause=list(Measurements=c("Micrometers", "Microscopes", "Inspectors"),
                            Materials=c("Alloys", "Lubricants", "Suppliers"),
                            Personnel=c("Shifts", "Supervisors", "Training", "Operators"),
                            Environment=c("Condensation", "Moisture"),
                            Methods=c("Brake", "Engager", "Angle"),
                            Machines=c("Speed", "Lathes", "Bits", "Sockets")),
                 effect="Low Sensitivity",
                 title = "Low Sensitivity with LC-MS/MS",
                 font = c(1, 3, 2), # values for the font to use. The values refer, in order, to branches, causes and effect.
                 cex = c(1, 0.7, 1)) # cex, values for the graphical character expansion. The values refer, in order, to branches, causes and effect

```

